source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DKTabView_Example', :exclusive => true do
  pod "DKTabView", :path => "../"
end

target 'DKTabView_Tests', :exclusive => true do
  pod "DKTabView", :path => "../"

  
end
